#!/bin/bash
ufw allow 22
ufw allow 53
ufw enable <<<y
psoutp=$(docker ps -a | grep " ns_data ")
      
if [[ -z "$psoutp" ]]; then
  echo "Need to run data container still."
  docker run -d --name ns_data runvnc/ns sleep 2147483647
else
  echo "Data container running."
fi
docker run --net container:name1.oic.io_vpn --volumes-from ns_data -d runvnc/ns

