#!/bin/bash
ufw allow 22
ufw allow 53
ufw enable
docker run -i -t --name ns_data runvnc/ns "sleep 2147483647"
docker run --volumes-from ns_data -i -t -p 53:53 -p 53:53/udp -p 14239:14239 runvnc/ns bash

