#!/bin/bash

revipv6() {
  ipv6calc --out revnibbles.arpa
  #sed -e "s/:/:0000/g" -e "s/:0*\([0-9a-f][0-9a-f][0-9a-f][0-9a-f]\)/:\1/g" -e "s/://g" | rev | sed -e "s/./&./g" -e "s/$/ip6.arpa/"
}

revipv4() {
  ipv6calc --out revnibbles.arpa
  #awk -F"." '{for(i=NF;i>0;i--) printf i!=1?$i".":"%s",$i}'
}

